"""
Pins `data/decisions.sample.jsonl` — the committed sample of the audit trail.

README and the written summary both call the decision log a product in its own right:
the evidence that a documented, consistent process was followed. That claim needs an
artefact a judge can open, and an artefact nobody checks is an artefact that rots.

The runtime log (`data/decisions.jsonl`) stays gitignored — an append-only operational
log should not be a tracked file. This pins the committed SAMPLE, regenerated by
`scripts/make_decisions_sample.py` from the real agent against the committed fixtures.

What is asserted is coverage of the paths that make the log worth having, not the exact
values: a sample showing only happy-path answers would prove nothing a screenshot could
not. The `at` timestamp is deliberately not asserted — it is a real generation time and
changes on every regeneration.
"""

import json
from pathlib import Path

import pytest

SAMPLE = Path(__file__).resolve().parents[1] / "data" / "decisions.sample.jsonl"

# Every field the audit trail promises. A record missing any of these cannot answer
# "what did you know, and what did you decide" — which is the whole point of the file.
REQUIRED_KEYS = {
    "at", "site_id", "site_name", "date", "question", "question_type",
    "escalated_from", "endpoint", "filter_type", "analytic_type", "granularity",
    "threshold_f_heat_index", "threshold_c_air", "rationale", "refusal",
    "refusal_message", "peak_f", "hours_above", "action", "band",
    "narration_source", "error",
}


@pytest.fixture(scope="module")
def records() -> list[dict]:
    assert SAMPLE.exists(), (
        f"{SAMPLE.name} is missing. README and the written summary both point at it — "
        f"regenerate with: python scripts/make_decisions_sample.py"
    )
    lines = [l for l in SAMPLE.read_text(encoding="utf-8").splitlines() if l.strip()]
    return [json.loads(line) for line in lines]


# ------------------------------------------------------------------ well-formedness

def test_every_line_is_valid_json():
    """JSONL, not JSON. One object per line, so a long-running log can be appended to
    and tailed without ever rewriting or re-parsing the whole file."""
    for i, line in enumerate(SAMPLE.read_text(encoding="utf-8").splitlines(), 1):
        if line.strip():
            assert isinstance(json.loads(line), dict), f"line {i} is not an object"


def test_the_sample_is_not_trivially_small(records):
    assert len(records) >= 6, "too few records to demonstrate anything"


def test_every_record_carries_every_promised_field(records):
    for i, record in enumerate(records, 1):
        missing = REQUIRED_KEYS - set(record)
        assert not missing, f"record {i} is missing {sorted(missing)}"


def test_no_api_key_leaked_into_the_sample():
    """This file ships in a public repo."""
    text = SAMPLE.read_text(encoding="utf-8").lower()
    for marker in ("api-key", "api_key", "fortyguard_api_key", "sk-", "gho_", "ghp_"):
        assert marker not in text, f"{marker!r} appears in a committed sample"


# ------------------------------------------------ the paths that make it worth having

def test_a_refusal_is_present(records):
    """The differentiator. Without one, the log only proves the tool answers — not that
    it declines when the data cannot support an answer."""
    refusals = [r for r in records if r["refusal"] is not None]
    assert refusals, "no refusal in the sample"
    for r in refusals:
        assert r["refusal_message"], "a refusal with no readable message is a bug"
        assert r["endpoint"] is None, "a refusal must not have reached the API"


def test_the_wrong_layer_refusal_is_present(records):
    """`wrong_layer_would_mislead` is the one that refuses a well-formed question the
    API would happily answer. It is the argument, so it must be in the sample."""
    assert any(r["refusal"] == "wrong_layer_would_mislead" for r in records)


def test_a_duration_question_used_exceedance(records):
    """The layer the default would have missed."""
    duration = [r for r in records
                if r["question_type"] == "duration" and not r["refusal"]]
    assert duration, "no answered duration question"
    assert all(r["analytic_type"] == "exceedance" for r in duration)


def test_a_comparison_question_is_present_across_more_than_one_site(records):
    comparison = [r for r in records if r["question_type"] == "comparison"]
    assert len({r["site_id"] for r in comparison}) > 1, (
        "a comparison across a single site demonstrates nothing"
    )


def test_an_escalation_is_recorded(records):
    """`escalated_from` proves the duration-marker rule overrode the classifier and
    said so, rather than silently rewriting the question."""
    escalated = [r for r in records if r["escalated_from"]]
    assert escalated, "no escalation in the sample"
    for r in escalated:
        assert r["question_type"] != r["escalated_from"]
        assert "duration marker" in r["rationale"]


def test_every_answered_record_states_its_layer_and_why(records):
    for r in records:
        if r["refusal"]:
            continue
        assert r["endpoint"] and r["filter_type"] and r["analytic_type"]
        assert len(r["rationale"]) > 60, "a layer choice with no rationale is not an audit"


def test_exceedance_records_carry_both_units_of_the_threshold(records):
    """The °F heat index the policy is written in, and the °C air temperature actually
    sent. Recording only one would hide the conversion that the whole project is about."""
    for r in records:
        if r["analytic_type"] == "exceedance" and not r["refusal"]:
            assert r["threshold_f_heat_index"] is not None
            assert r["threshold_c_air"] is not None
            assert r["threshold_c_air"] < 60.0, "a °C threshold above 60 is Fahrenheit"


def test_the_sample_was_generated_offline(records):
    """narration_source must be the template: the sample has to be reproducible by a
    judge with no API keys of any kind."""
    assert all(r["narration_source"] == "template" for r in records)


def test_no_record_errored(records):
    assert all(r["error"] is None for r in records), (
        "the sample should be regenerated cleanly, not shipped with errors in it"
    )
