"""
render_evidence.py — expand [[EV:ID]] citation markers into numbered markdown footnotes.

Run:  python scripts/render_evidence.py docs/submission-summary-v2.md            (to stdout)
      python scripts/render_evidence.py README.md --out build/README.md
      python scripts/render_evidence.py README.md --in-place
      python scripts/render_evidence.py README.md --check                        (CI gate)

WHY THIS EXISTS
Prose wants to read `48 US workers died of environmental heat in 2024`. A judge wants to
see where 48 came from. Writing the URL inline gets both wrong: the sentence turns into a
link farm, and the figure still detaches from its source the moment either is edited by
hand. So the prose carries `[[EV:HARM-01]]` — a claim id, not a number and not a URL — and
this script resolves it against `data/evidence/claims.json` at render time. The number, the
source title, the data year and the URL are all read from the registry, so a correction
lands in one file and propagates everywhere.

`--check` resolves every marker and writes nothing, which is the form CI wants: an
unresolvable citation reads exactly like a real one, so it has to fail the build rather
than warn. `tests/test_evidence.py` asserts the same thing over the four files allowed to
cite the registry; this runs it over any file you point it at.

STDOUT BY DEFAULT, deliberately. Rendering is not editing: the file carrying the markers is
the master and the rendered copy is an artefact. Overwriting the master needs `--in-place`
typed out, because a marker replaced by a footnote cannot be re-rendered.

Two things travel with the number and are not optional. A claim whose most recent data is
older than three years is marked [STALE: year] — an unflagged stale figure is worse than a
stale one, because the flag is what a reader trusts instead of reading the date. And a
GENERAL_POPULATION claim carries its caveat into the footnote, because Maricopa County's
death counts are not worker figures and the county does not record occupation.

Standard library only. This has to run in CI with nothing installed.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "data" / "evidence" / "claims.json"

MARKER = re.compile(r"\[\[EV:([A-Z]{3,5}-\d{2})\]\]")

SOURCES_HEADING = "## Sources"
SENTINEL = "<!-- sources generated by scripts/render_evidence.py from data/evidence/claims.json -->"


def load_claims(registry: Path = REGISTRY) -> dict[str, dict]:
    """The registry, indexed by claim id."""
    data = json.loads(registry.read_text(encoding="utf-8"))
    return {claim["id"]: claim for claim in data["claims"]}


def markers_in(text: str) -> list[tuple[int, str]]:
    """Every [[EV:ID]] in the text, in reading order, with its line number."""
    found: list[tuple[int, str]] = []
    for lineno, line in enumerate(text.splitlines(), 1):
        found.extend((lineno, claim_id) for claim_id in MARKER.findall(line))
    return found


def numbering(text: str) -> dict[str, int]:
    """Footnote numbers by first appearance. A repeated citation reuses its number."""
    order: dict[str, int] = {}
    for _, claim_id in markers_in(text):
        order.setdefault(claim_id, len(order) + 1)
    return order


def footnote(claim: dict, number: int) -> str:
    """One Sources line: value — source_title, data year, URL, then the flags."""
    line = (
        f"[^{number}]: **{claim['value']}** — {claim['source_title']}, "
        f"{claim['data_year']}. <{claim['source_url']}>"
    )
    if claim.get("stale"):
        line += f" · **[STALE: {claim['data_year']}]**"
    if claim["scope"] == "GENERAL_POPULATION":
        line += f" · **[GEN POP]** {claim.get('caveat', '')}".rstrip()
    return line


def strip_previous_block(text: str) -> str:
    """Drop a Sources block this script wrote earlier, so re-rendering is idempotent.

    Only a block carrying the sentinel is removed. A hand-written `## Sources` section is
    somebody's prose and is left exactly where it is.
    """
    if SENTINEL not in text:
        return text
    lines = text.splitlines()
    cut = next(i for i, line in enumerate(lines) if SENTINEL in line)
    for i in range(cut, -1, -1):
        if lines[i].strip() == SOURCES_HEADING:
            cut = i
            break
    return "\n".join(lines[:cut]).rstrip() + "\n"


def render(text: str, claims: dict[str, dict]) -> str:
    """Markers to footnote references, plus the appended Sources block.

    A document with no markers left is returned untouched. That covers the file that has
    already been rendered: its markers are now footnote references, so re-rendering would
    otherwise strip the previous block and rebuild nothing, deleting the sources it just
    wrote. Running this twice on the same file has to be a no-op.
    """
    if not markers_in(text):
        return text if text.endswith("\n") else text + "\n"

    text = strip_previous_block(text)
    order = numbering(text)
    body = MARKER.sub(lambda m: f"[^{order[m.group(1)]}]", text).rstrip()

    block = [SOURCES_HEADING, "", SENTINEL, ""]
    block += [footnote(claims[claim_id], number) for claim_id, number in order.items()]
    return body + "\n\n" + "\n".join(block) + "\n"


def report_unresolved(path: Path, text: str, claims: dict[str, dict]) -> list[str]:
    """Markers pointing at claims that are not in the registry."""
    return [
        f"{path}:{lineno}: [[EV:{claim_id}]] is not in "
        f"{REGISTRY.relative_to(ROOT).as_posix()}"
        for lineno, claim_id in markers_in(text)
        if claim_id not in claims
    ]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("path", type=Path, help="markdown file containing [[EV:ID]] markers")
    ap.add_argument("--check", action="store_true",
                    help="verify every marker resolves, write nothing, exit 1 on failure")
    ap.add_argument("--in-place", action="store_true",
                    help="rewrite the input file instead of printing to stdout")
    ap.add_argument("--out", type=Path, metavar="PATH",
                    help="write the rendered document to PATH")
    ap.add_argument("--registry", type=Path, default=REGISTRY,
                    help=f"claims registry (default: {REGISTRY.relative_to(ROOT).as_posix()})")
    args = ap.parse_args()

    if args.in_place and args.out:
        print("--in-place and --out are mutually exclusive", file=sys.stderr)
        return 2
    if not args.path.exists():
        print(f"no such file: {args.path}", file=sys.stderr)
        return 2
    if not args.registry.exists():
        print(f"no registry at {args.registry}", file=sys.stderr)
        return 2

    claims = load_claims(args.registry)
    text = args.path.read_text(encoding="utf-8")
    found = markers_in(text)
    unresolved = report_unresolved(args.path, text, claims)

    for problem in unresolved:
        print(problem, file=sys.stderr)
    if unresolved:
        print(f"\n{len(unresolved)} unresolvable citation(s) in {args.path} — "
              f"add them to {args.registry.name} or fix the marker", file=sys.stderr)
        return 1

    distinct = numbering(text)
    stale = [cid for cid in distinct if claims[cid].get("stale")]
    gen_pop = [cid for cid in distinct
               if claims[cid]["scope"] == "GENERAL_POPULATION"]

    already_rendered = not found and SENTINEL in text

    if args.check:
        print(f"{args.path}: {len(found)} marker(s), {len(distinct)} distinct claim(s), "
              f"all resolved", file=sys.stderr)
        if already_rendered:
            print("  already rendered — footnotes present, no markers left to expand",
                  file=sys.stderr)
        if stale:
            print(f"  stale, will be flagged: {', '.join(sorted(stale))}", file=sys.stderr)
        if gen_pop:
            print(f"  general-population, caveat travels with it: "
                  f"{', '.join(sorted(gen_pop))}", file=sys.stderr)
        return 0

    rendered = render(text, claims)

    if args.in_place:
        args.path.write_text(rendered, encoding="utf-8")
        destination = args.path
    elif args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(rendered, encoding="utf-8")
        destination = args.out
    else:
        sys.stdout.write(rendered)
        destination = None

    where = f" -> {destination}" if destination else ""
    print(f"{args.path}: {len(found)} marker(s), {len(distinct)} footnote(s)"
          f"{where}", file=sys.stderr)
    if already_rendered:
        print("  already rendered — left unchanged", file=sys.stderr)
    if stale:
        print(f"  flagged stale: {', '.join(sorted(stale))}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
